export const GET_BMS_URL = 'GET_BMS_URL';
export const AUTO_PAY_STATUS = 'AUTO_PAY_STATUS';
export const BMS_VERIFICATION_STATUS = 'BMS_VERIFICATION_STATUS';
export const ADD_CALL_TO_QUEUE = 'ADD_CALL_TO_QUEUE';
export const DOC_POINT_BMS_URL = 'DOC_POINT_BMS_URL';
export const MY_BOOKINGS_BMS_API = 'MY_BOOKINGS_BMS_API';
export const PENDING_PF_LEAD = 'PENDING_PF_LEAD';
export const PENDING_DOC_LEAD = 'PENDING_DOC_LEAD';
export const GET_CJ_URL = 'GET_CJ_URL';
export const GET_VERIFICATION_CAMPAIGN = 'GET_VERIFICATION_CAMPAIGN';

export const DEFAULT_TIMEOUT = 10;
